### ISSUE TITLE
The CTI and XML formats are no longer supported.

### ISSUE THREAD

**Issue by Jeason-star** [DeltaComb/DeePFGM#1]
我直接运行run.sh首先会出现：
```
Traceback (most recent call last):
  File "flareD.py", line 21, in <module>
    cbDict = read_commonDict.read_commonDict("commonDict.txt")
  File "/home/nuaa/DeePFGM-main/Flare/read_commonDict.py", line 14, in read_commonDict
    cbDict['nSpeMech'] = ct.Solution(cbDict['chemMech']).n_total_species
  File "cantera/solutionbase.pyx", line 37, in cantera.solutionbase._SolutionBase.__cinit__
  File "cantera/solutionbase.pyx", line 95, in cantera.solutionbase._SolutionBase._cinit
  File "cantera/solutionbase.pyx", line 180, in cantera.solutionbase._SolutionBase._init_yaml
cantera._utils.CanteraError: 
*******************************************************************************
CanteraError thrown by newSolution:
The CTI and XML formats are no longer supported.
*******************************************************************************
```
上面这样的报错，错误提示表明目前我用的cantera版本不支持.xml格式的机理文件，于是我将commonDict.txt中的
```
    #---------------cantera设置-------------------#
    #机理文件路径/文件名
    'chemMech' : 'gri30.xml',
```
改为了：
```

    #---------------cantera设置-------------------#
    #机理文件路径/文件名
    'chemMech' : 'gri30.yaml',
```
就不会再报上述错误了，但我不清楚这样改会不会存在问题，因为我对cantera的中机理文件并不熟悉。

上述错误解决后，再次运行时又出现了如下错误：
```
Traceback (most recent call last):
  File "flareD.py", line 25, in <module>
    multiProcessing_canteraSim.canteraSim(cbDict,solFln)
  File "/home/nuaa/DeePFGM-main/Flare/multiProcessing_canteraSim.py", line 223, in canteraSim
    gas_fuel = ct.Solution(chemMech, 'gri30_multi')
  File "cantera/solutionbase.pyx", line 37, in cantera.solutionbase._SolutionBase.__cinit__
  File "cantera/solutionbase.pyx", line 95, in cantera.solutionbase._SolutionBase._cinit
  File "cantera/solutionbase.pyx", line 180, in cantera.solutionbase._SolutionBase._init_yaml
cantera._utils.CanteraError: 
*******************************************************************************
InputFileError thrown by AnyValue::getMapWhere:
Error on line 18 of /home/nuaa/miniconda3/envs/deepflame/lib/python3.8/site-packages/cantera/data/gri30.yaml:
List does not contain a map where 'name' = 'gri30_multi'
|  Line |
|    13 | date: Wed, 11 Dec 2019 16:59:02 -0500
|    14 | 
|    15 | units: {length: cm, time: s, quantity: mol, activation-energy: cal/mol}
|    16 | 
|    17 | phases:
>    18 > - name: gri30
          ^
|    19 |   thermo: ideal-gas
|    20 |   elements: [O, H, C, N, Ar]
|    21 |   species: [H2, H, O, O2, OH, H2O, HO2, H2O2, C, CH, CH2, CH2(S), CH3, CH4,
*******************************************************************************
```
上述错误提示表明：在gri30.yaml机理文件中找不到gri30_multi，我在网上查找发现cantera在2.5的版本就已经弃用了gri30_multi，如下所示
```
Cantera version
2.5.0a3

Operating System / Python/MATLAB version
all

Expected Behavior
The gri30_mix and gri30_multi phases are deprecated and are not part of all gri30.yaml versions (the version in test/work/python defines those, the default version does not). For consistency, all instances should be removed for 2.5, as the transport model can be specified using a flag. I.e. the differentiation of transport models in phases is largely obsolete:
```
于是我将程序中的gri30_multi都改成了gri30，但我不清楚这样改是否合理。

改完之后能正常运行了，期间会出现两张图，但在最后又出现了下面的报错：
```
Reading unit01_h01 ... 

Traceback (most recent call last):
  File "flareD.py", line 34, in <module>
    assemble.assemble(cbDict,solFln)
  File "/home/nuaa/DeePFGM-main/Flare/assemble.py", line 9, in assemble
    M = np.loadtxt(solFln + "/" + 'unit01_h' + '%02d' % (i+1) + '.dat')
  File "/home/nuaa/miniconda3/envs/deepflame/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/nuaa/miniconda3/envs/deepflame/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/nuaa/miniconda3/envs/deepflame/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/nuaa/miniconda3/envs/deepflame/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ./canteraData//unit01_h01.dat not found.
```
错误显示在canteraData文件夹下找到unit01_h01.dat，这个文件我看了一下确实没有，但canteraData文件夹下已经生成了许多.data文件，以及flare.tbl文件。
所以没有生成unit01_h01.dat文件的原因是什么？以及这个文件是用来做什么的？

**Comment by TimoLin** [comment]
提供运行环境：
===========
终端下输入下面的命令，然后将输出贴上来
```sh
conda  activate deepflame
python --version
python -c "import cantera as ct; print(ct.sys.version_info)"
```

**Comment by Jeason-star** [comment]
输入后是这样的：
```
(deepflame) nuaa@nuaa-HP:~/DeePFGM-main/Flare$ python --version
Python 3.8.18
(deepflame) nuaa@nuaa-HP:~/DeePFGM-main/Flare$ python -c "import cantera as ct; print(ct.sys.version)"
3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0]
```

**Comment by TimoLin** [comment]
>  CanteraError thrown by newSolution:
The CTI and XML formats are no longer supported.

Cantera版本过高, 原repo使用的应该是2.6.0，建议使用相同的版本。
重新安装`cantera-2.6.0`和其他依赖
```sh
conda install -c cantera cantera=2.6.0
conda install matplotlib
```
拉取最新的修改：
```sh
cd DeePFGM
git pull
```
